name: build and push dice-java

on:
  push:
    branches:
      - main
    paths:
      - "src/dice-java/**"

jobs:
  # test locally with: `act -s GITHUB_TOKEN=$(gh auth token) --env github.actor=$USER`
  # get 'act': https://nektosact.com/installation/index.html
  build-and-push-dice-java:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Build image
        run: task clients:build-dice-java
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push to registry
        run: task clients:push-dice-java
